---
- hosts: all
  user: root
  become: true
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  vars_files:
  - vars/dev-secrets.yml
  - vars/graylog.yml
  - vars/versions.yml
