---
- name: copy 90-graylog.conf
  template: src=templates/rsyslog/90-graylog.conf.j2
            dest=/etc/rsyslog.d/90-graylog.conf
            owner=root
            group=root
            mode=0644
  notify: restart rsyslog
